version: '3'

services:
  main:
    build: .
    env_file:
        - .docker-env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - default
  db:
    image: postgres:11.4-alpine
    env_file:
      - .docker-env
    volumes:
      - main_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:4-alpine
    command: redis-server --requirepass REDIS

volumes:
  main_pgdata:
